export const MainpageActionTypes = {
  SET_CONTACTS_TO_ARRAY: 'SET_CONTACTS_TO_ARRAY',
  SET_OBJ_TO_OBJ: 'SET_OBJ_TO_OBJ',
  SET_PAGE_TO_PAGE: 'SET_PAGE_TO_PAGE',
  SET_SEARCHFIELD_TO_SEARCHFIELD: 'SET_SEARCHFIELD_TO_SEARCHFIELD',
  SET_COUNT_TO_COUNT: 'SET_COUNT_TO_COUNT',
  SET_DIS1_TO_DIS1: 'SET_DIS1_TO_DIS1',
  SET_ID_TO_NUM: 'SET_ID_TO_NUM',
  SET_DIS3_TO_DIS3: 'SET_DIS3_TO_DIS3',
  SET_SEL_TO_ID: 'SET_SEL_TO_ID',
  SET_MAXPAGE_TO_ARR: 'SET_MAXPAGE_TO_ARR',
};
